### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Joana Silva Souto",
  "email": "joana.silva.souto@example.com",
  "address": "123 Oak St, Anytown, USA",
  "dateOfBirth": "1997-01-22",
  "registeredDate": "2025-01-10"
}

### Test with existing email (should return error)
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "address": "123 Main St, Anytown, USA",
  "dateOfBirth": "1990-01-01",
  "registeredDate": "2024-11-20"
}

### Test without email (should return error)
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe",
  "email": "",
  "address": "123 Main St, Anytown, USA",
  "dateOfBirth": "1990-01-01",
  "registeredDate": "2024-11-20"
}

### Test without email (should return error)
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Maria Maria",
  "email": "maria_maria@example.com",
  "address": "123 Sacomã",
  "dateOfBirth": "1996-01-01",
  "registeredDate": "2025-11-20"
}